name: .NET Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  pull-request-check:
    
    strategy:
      matrix:
        configuration: [ Release ]
        platform: [ x64, x86, arm64 ]

    runs-on: windows-latest
    
    env:
      SOLUTION: source/Monaco.sln
      PROJECT_FILE: source/Monaco/Monaco.csproj
      VERSION: 1.0.${{ github.run_number }}
    
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Setup MSBuild.exe
        uses: microsoft/setup-msbuild@v1.1

      - name: Restore dependencies
        run: msbuild ${{ env.SOLUTION }} /t:Restore /p:Configuration=$env:Configuration
        env:
          Configuration: ${{ matrix.configuration }}

      # Create the app package by building and packaging the project
      - name: Create the app package
        run: msbuild -t:pack ${{ env.SOLUTION }} /p:PackageVersion=${{ env.VERSION }} /p:Configuration=$env:Configuration /p:Platform=$env:Platform  /p:AppxPackageDir="$env:Appx_Package_Dir"
        env:
          Appx_Package_Dir: Packages\
          Configuration: ${{ matrix.configuration }}
          Platform: ${{ matrix.platform }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
